// <auto-generated />
using System;
using CzechUp.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CzechUp.EF.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250406215035_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CzechUp.EF.Models.GeneralExercise", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnswerOptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("GeneralExercises");
                });

            modelBuilder.Entity("CzechUp.EF.Models.GeneralOriginalWord", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("GeneralTopicGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageLevelGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("GeneralTopicGuid");

                    b.HasIndex("LanguageLevelGuid");

                    b.ToTable("GeneralOriginalWords");
                });

            modelBuilder.Entity("CzechUp.EF.Models.GeneralTopic", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("GeneralTopics");
                });

            modelBuilder.Entity("CzechUp.EF.Models.GeneralWordExample", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("GeneralOriginalWordGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalExample")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranslatedExample")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("GeneralOriginalWordGuid");

                    b.HasIndex("LanguageGuid");

                    b.ToTable("GeneralWordExamples");
                });

            modelBuilder.Entity("CzechUp.EF.Models.GeneralWordForm", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("GeneralOriginalWordGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WordForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WordNumber")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.HasIndex("GeneralOriginalWordGuid");

                    b.ToTable("GeneralWordForms");
                });

            modelBuilder.Entity("CzechUp.EF.Models.GeneralWordTranslation", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("GeneralOriginalWordGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("GeneralOriginalWordGuid");

                    b.HasIndex("LanguageGuid");

                    b.ToTable("GeneralWordTranslations");
                });

            modelBuilder.Entity("CzechUp.EF.Models.Language", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("CzechUp.EF.Models.LanguageLevel", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("LanguageLevels");
                });

            modelBuilder.Entity("CzechUp.EF.Models.Rule", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("CzechUp.EF.Models.TagType", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("TagTypeEnum")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.ToTable("TagTypes");
                });

            modelBuilder.Entity("CzechUp.EF.Models.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequiredLanguageLevelGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TranslatedLanguageGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("RequiredLanguageLevelGuid");

                    b.HasIndex("TranslatedLanguageGuid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserExercise", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CorrectAnswerCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("GeneralExerciseGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("WrongAnswerCount")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.HasIndex("GeneralExerciseGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("UserExercises");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserOriginalWord", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("GeneralOriginalWordGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LanguageLevelGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserTopicGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("GeneralOriginalWordGuid");

                    b.HasIndex("LanguageLevelGuid");

                    b.HasIndex("UserGuid");

                    b.HasIndex("UserTopicGuid");

                    b.ToTable("UserOriginalWords");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserRuleNote", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RuleGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("RuleGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("UserRuleNotes");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserTag", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("UserGuid");

                    b.ToTable("UserTags");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserTopic", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("GeneralTopicGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("GeneralTopicGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("UserTopics");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserWordExample", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("OriginalExample")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranslatedExample")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserOriginalWordGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("UserOriginalWordGuid");

                    b.ToTable("UserWordExamples");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserWordForm", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserOriginalWordGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("WordForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("UserOriginalWordGuid");

                    b.ToTable("UserWordForms");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserWordTranslation", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserOriginalWordGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("UserGuid");

                    b.HasIndex("UserOriginalWordGuid");

                    b.ToTable("UserWordTranslations");
                });

            modelBuilder.Entity("UserExerciseUserTag", b =>
                {
                    b.Property<Guid>("UserExerciseGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserTagGuid")
                        .HasColumnType("uuid");

                    b.HasKey("UserExerciseGuid", "UserTagGuid");

                    b.HasIndex("UserTagGuid");

                    b.ToTable("UserExerciseUserTag");
                });

            modelBuilder.Entity("UserOriginalWordUserTag", b =>
                {
                    b.Property<Guid>("UserOriginalWordGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserTagGuid")
                        .HasColumnType("uuid");

                    b.HasKey("UserOriginalWordGuid", "UserTagGuid");

                    b.HasIndex("UserTagGuid");

                    b.ToTable("UserOriginalWordUserTag");
                });

            modelBuilder.Entity("UserRuleUserTag", b =>
                {
                    b.Property<Guid>("UserRuleGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserTagGuid")
                        .HasColumnType("uuid");

                    b.HasKey("UserRuleGuid", "UserTagGuid");

                    b.HasIndex("UserTagGuid");

                    b.ToTable("UserRuleUserTag");
                });

            modelBuilder.Entity("UserTagTagTypes", b =>
                {
                    b.Property<Guid>("TagTypeGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserTagGuid")
                        .HasColumnType("uuid");

                    b.HasKey("TagTypeGuid", "UserTagGuid");

                    b.HasIndex("UserTagGuid");

                    b.ToTable("UserTagTagTypes");
                });

            modelBuilder.Entity("UserTopicUserTag", b =>
                {
                    b.Property<Guid>("UserTagGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserTopicGuid")
                        .HasColumnType("uuid");

                    b.HasKey("UserTagGuid", "UserTopicGuid");

                    b.HasIndex("UserTopicGuid");

                    b.ToTable("UserTopicUserTag");
                });

            modelBuilder.Entity("CzechUp.EF.Models.GeneralOriginalWord", b =>
                {
                    b.HasOne("CzechUp.EF.Models.GeneralTopic", "GeneralTopic")
                        .WithMany()
                        .HasForeignKey("GeneralTopicGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.LanguageLevel", "LanguageLevel")
                        .WithMany()
                        .HasForeignKey("LanguageLevelGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralTopic");

                    b.Navigation("LanguageLevel");
                });

            modelBuilder.Entity("CzechUp.EF.Models.GeneralWordExample", b =>
                {
                    b.HasOne("CzechUp.EF.Models.GeneralOriginalWord", "GeneralOriginalWord")
                        .WithMany()
                        .HasForeignKey("GeneralOriginalWordGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralOriginalWord");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("CzechUp.EF.Models.GeneralWordForm", b =>
                {
                    b.HasOne("CzechUp.EF.Models.GeneralOriginalWord", "GeneralOriginalWord")
                        .WithMany()
                        .HasForeignKey("GeneralOriginalWordGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralOriginalWord");
                });

            modelBuilder.Entity("CzechUp.EF.Models.GeneralWordTranslation", b =>
                {
                    b.HasOne("CzechUp.EF.Models.GeneralOriginalWord", "GeneralOriginalWord")
                        .WithMany()
                        .HasForeignKey("GeneralOriginalWordGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralOriginalWord");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("CzechUp.EF.Models.User", b =>
                {
                    b.HasOne("CzechUp.EF.Models.LanguageLevel", "RequiredLanguageLevel")
                        .WithMany()
                        .HasForeignKey("RequiredLanguageLevelGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.Language", "TranslatedLanguage")
                        .WithMany()
                        .HasForeignKey("TranslatedLanguageGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequiredLanguageLevel");

                    b.Navigation("TranslatedLanguage");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserExercise", b =>
                {
                    b.HasOne("CzechUp.EF.Models.GeneralExercise", "GeneralExercise")
                        .WithMany()
                        .HasForeignKey("GeneralExerciseGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralExercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserOriginalWord", b =>
                {
                    b.HasOne("CzechUp.EF.Models.GeneralOriginalWord", "GeneralOriginalWord")
                        .WithMany()
                        .HasForeignKey("GeneralOriginalWordGuid");

                    b.HasOne("CzechUp.EF.Models.LanguageLevel", "LanguageLevel")
                        .WithMany()
                        .HasForeignKey("LanguageLevelGuid");

                    b.HasOne("CzechUp.EF.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.UserTopic", "UserTopic")
                        .WithMany()
                        .HasForeignKey("UserTopicGuid");

                    b.Navigation("GeneralOriginalWord");

                    b.Navigation("LanguageLevel");

                    b.Navigation("User");

                    b.Navigation("UserTopic");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserRuleNote", b =>
                {
                    b.HasOne("CzechUp.EF.Models.Rule", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserTag", b =>
                {
                    b.HasOne("CzechUp.EF.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserTopic", b =>
                {
                    b.HasOne("CzechUp.EF.Models.GeneralTopic", "GeneralTopic")
                        .WithMany()
                        .HasForeignKey("GeneralTopicGuid");

                    b.HasOne("CzechUp.EF.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralTopic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserWordExample", b =>
                {
                    b.HasOne("CzechUp.EF.Models.UserOriginalWord", "UserOriginalWord")
                        .WithMany()
                        .HasForeignKey("UserOriginalWordGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserOriginalWord");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserWordForm", b =>
                {
                    b.HasOne("CzechUp.EF.Models.UserOriginalWord", "UserOriginalWord")
                        .WithMany()
                        .HasForeignKey("UserOriginalWordGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserOriginalWord");
                });

            modelBuilder.Entity("CzechUp.EF.Models.UserWordTranslation", b =>
                {
                    b.HasOne("CzechUp.EF.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.UserOriginalWord", "UserOriginalWord")
                        .WithMany()
                        .HasForeignKey("UserOriginalWordGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserOriginalWord");
                });

            modelBuilder.Entity("UserExerciseUserTag", b =>
                {
                    b.HasOne("CzechUp.EF.Models.UserExercise", null)
                        .WithMany()
                        .HasForeignKey("UserExerciseGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.UserTag", null)
                        .WithMany()
                        .HasForeignKey("UserTagGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserOriginalWordUserTag", b =>
                {
                    b.HasOne("CzechUp.EF.Models.UserOriginalWord", null)
                        .WithMany()
                        .HasForeignKey("UserOriginalWordGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.UserTag", null)
                        .WithMany()
                        .HasForeignKey("UserTagGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserRuleUserTag", b =>
                {
                    b.HasOne("CzechUp.EF.Models.Rule", null)
                        .WithMany()
                        .HasForeignKey("UserRuleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.UserTag", null)
                        .WithMany()
                        .HasForeignKey("UserTagGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserTagTagTypes", b =>
                {
                    b.HasOne("CzechUp.EF.Models.TagType", null)
                        .WithMany()
                        .HasForeignKey("TagTypeGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.UserTag", null)
                        .WithMany()
                        .HasForeignKey("UserTagGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserTopicUserTag", b =>
                {
                    b.HasOne("CzechUp.EF.Models.UserTag", null)
                        .WithMany()
                        .HasForeignKey("UserTagGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CzechUp.EF.Models.UserTopic", null)
                        .WithMany()
                        .HasForeignKey("UserTopicGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
